---
title: "Design Specification Document"
author: "Rebecca DeMarco"
date: "August 25, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Revision History 
Date      | Version | Description       | Author 
----------|---------|-------------------|----------------
8/25/2016 | draft   | Establishing draft| Rebecca DeMarco 
8/26/2016 | draft   | Editing draft     | Rebecca DeMarco 

### 1.0 Introduction 
#### 1.1 Purpose of Document 
#### 1.2 Scope of the Development Project 
#### 1.3 Definitions and Acronyms 

### 2.0 System Architecture 
//block diagram that shows all the major components of the system 
//narrative discussing architecture 

### 3.0 Technical Environment 
#### 3.1 Platforms 
#### 3.2 Tools 

### 4.0 Software Design 
#### 4.1 Sequence Diagrams 
#### 4.2 Design Details for Software Components 
#### 4.3 Database Design 

### 5.0 User Interface Design 

#### 5.1 Iteration 1 - Initial Mockup 
//summary of the development for the first iteration of design  
##### 5.1.1 Iteration 1: User Story Trace to UI 
##### 5.1.2 Iteration 1: Human Factors Principles 
##### 5.1.3 Iteration 1: Human Factors Methods 

#### 5.2 Iteration 2 - Human Factors Reassement and Product Owner/User Feedback
//Summary of the design Changes 
##### 5.2.1 Iteration 2: Design Changes - Human Factors Principles 
##### 5.2.2 Iteration 2: Design Changes - Human Factors Methods 
##### 5.2.3 Iteration 2: Design Changes - Product Owner/End User Feedback 
##### 5.2.4 Iteration 2: User Story Trace to UI 

#### 5.3 Iteration 3 - Usability Testing 
//Summary of the design Changes 
##### 5.3.1 Iteration 3: Design Changes - Human Factors Principles 
##### 5.3.2 Iteration 3: Design Changes - Human Factors Methods 
##### 5.3.3 Iteration 3: Design Changes - Product Owner/End User Feedback 
##### 5.3.4 Iteration 3: User Story Trace to UI 

#### 5.4 Iteration 4 - Final Design November 2016
//Summary of the design Changes 
##### 5.4.1 Iteration 3: Design Changes - Human Factors Principles 
##### 5.4.2 Iteration 3: Design Changes - Human Factors Methods 
##### 5.4.3 Iteration 3: Design Changes - Product Owner/End User Feedback 
##### 5.4.4 Iteration 3: User Story Trace to UI 
