---
title: "Developer Guide"
author: "Rebecca DeMarco"
date: "August 26, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**International Space Station Data Visualization Project Developer Guide** 

### Revision History 
Date      | Version | Description       | Author 
----------|---------|-------------------|----------------
8/26/2016 | draft   | Establishing Draft| Rebecca DeMarco 



### Introduction 

#### 1.1 Purpose of Document 
This document is to help future developers pick up the work on this project. It is meant as a resource to orientate them to the project. 

#### 1.2 Intended Auidience 
The intended audience of this document is people who are assigned to work on the project. 

#### 1.3 Document Conventions 

### 2.0 Development Process
The development process used for the development of the Fall 2016 iteration of the web application was Scrum. 

### 3.0 Development Tools 
* R 3.3.0 or greater 
* Python 3.X via Anaconda 
* Neo4j
* MongoDB 

### 4.0 Project Documentation 
* User Story Specification Document
* Design Specification Document 
* Test Document 

### 5.0 Project Status
//status of the project as of December 2016
